### ISSUE TITLE
Apartment Storage Box Bug

### ISSUE THREAD

**Issue by SSteffan** [vingard/impulse-issues#100]
**Describe the bug**
You can not Access the Storage Box In an Apartment

**To reproduce**
Steps to reproduce the behaviour:
1. Buy an Apartment
2. Press F4
3. Go to "Actions"
4. Click "Sell all doors"
5. Try to Open Storage Box

**Expected behaviour**
You Should be able to Access the chest, because this Command Does not Sell apartment Doors.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
With this Bug you can not use the Storage Box unless you sell and rebuy the apartment.

**Comment by vingard** [comment]
We'd need details on the exact apartment to re-produce this issue.
