### ISSUE TITLE
Advert Bug

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#102]
**Describe the bug**
You can make adverts while you are in jail

**To reproduce**
Steps to reproduce the behaviour:
1. Go CWU
2. Get arrested
3.  Do an advert
4. Wait for the advert to appear
5. See error

**Expected behaviour**
Clearly you should be blocked from doing adverts while in jail.

**Screenshots**
Not needed

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
N/A

**Comment by vingard** [comment]
Fixed in 1.7. :)
