### ISSUE TITLE
OTA/CP running sounds are local

### ISSUE THREAD

**Issue by Tadeus2907** [vingard/impulse-issues#103]
**Describe the bug**
The OTA/CP running sounds only appear for you, I have tried this out and I cannot hear any other CPs/OTA running sounds.
**To reproduce**
Steps to reproduce the behaviour:
1. Go, in-game.
2. Listen if CPs/OTA have a running sounds.

**Expected behaviour**
CPs/OTA running sounds, should not be local and should work for everyone.

**impulse version (press F1 in the bottom right): 1.62""

**Comment by vingard** [comment]
This is intended due to the source engine sound limit being only 64 active sounds.
