### ISSUE TITLE
Vice Armband Issue

### ISSUE THREAD

**Issue by SSteffan** [vingard/impulse-issues#105]
**Describe the bug**
No matter What rank A Vice Unit is Their Armband says i4

**To reproduce**
Steps to reproduce the behaviour:
1. Go onto CP Job
2. Select Vice Division
3. Click "Become Vice [rank here]"
4. Look at the armband

**Expected behaviour**
The Armband Should Reflect the Rank of the Unit.

**Screenshots**
https://cdn.discordapp.com/attachments/847898075669594112/850155805692133396/20210604003506_1.jpg

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
Not Sure how long this Has been an Issue
I did notice that Vice uses a different Coloured Armband, so That might be the Problem as the Higher Rank Armband Textures May not Exist.

**Comment by vingard** [comment]
This is intended. For technical reasons this is not a simple fix.
