### ISSUE TITLE
Bypassing spawning explosive barrels.

### ISSUE THREAD

**Issue by SpriteCran** [vingard/impulse-issues#107]
**Describe the Bug**
This bug allows you to bypass the FPP blacklist and spawn explosive barrels.

Steps to reproduce the behaviour:
1. Open the console
2. Type in "wire_door_model models/props_c17/oildrum001_explosive.mdl"
3. Go to Doors in the Wire section
4. Spawn the door
5. Barrel.

**Expected behaviour**
It's exactly like an explosive barrel in the spawn menu, ignites & explodes after being shot.

**Screenshots**
https://cdn.discordapp.com/attachments/795103144249131058/856599013523324958/unknown.png
https://cdn.discordapp.com/attachments/795103144249131058/856599077957795870/unknown.png

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
N/A

**Comment by vingard** [comment]
Fixed in 1.7 (wiremod sux)
