### ISSUE TITLE
ECHO-OWS, uses the AR2 holster position.

### ISSUE THREAD

**Issue by Tadeus2907** [vingard/impulse-issues#109]
**Describe the bug**
The ECHO-OWS, uses the AR2 holster animation for the SMG.

**To reproduce**
Steps to reproduce the behaviour:
1. Go on ECHO-OWS
2. Draw your weapon.

**Expected behaviour**
ECHO-OWS, should use the idle_smg1 animation.

**Screenshots**
https://prnt.sc/17uwl55

**impulse version (press F1 in the bottom right):**
1.62

**Comment by vingard** [comment]
This won't be fixed.
