### ISSUE TITLE
Unregistered combine doors.

### ISSUE THREAD

**Issue by zachun** [vingard/impulse-issues#118]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Go to North Road.
2. Press F2 on the hard point door 
3. Notice that CPs are not able to open the door.

**Expected behaviour**
Civil Protection & Overwatch Transhuman Arm should be able to open it not only to kick it.

**Screenshots**
https://imgur.com/IFWUCWR
https://imgur.com/uyMNCSx

**impulse version (press F1 in the bottom right):**
1.7

**Lua error**
N/A

**Additional context**
Seems like this is not the only door that is not registered as a combine door.

**Comment by vingard** [comment]
fixed in 1.71 thanks
