### ISSUE TITLE
Purchasable Doors

### ISSUE THREAD

**Issue by egerdnc** [vingard/impulse-issues#119]
**Describe the bug**
There are some doors you can own but those doors are supposed to be not ownable.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to RDC'
2. Click on 'F2'
3. Scroll down to 'Buy the door'

**Expected behaviour**
There are some doors you can own but those doors are supposed to be not ownable.

**Screenshots**
https://prnt.sc/1kji8zj

**impulse version (press F1 in the bottom right):**
1.7

**Lua error**
No errors.

**Additional context**

**Comment by egerdnc** [comment]
EXTRA: Also this idk the apartment name but it's next to the nexus
https://prnt.sc/1kjmevu

**Comment by vingard** [comment]
Fixed, thanks.

**Comment by egerdnc** [comment]
People are still able to buy these doors and this place belongs to Civil Medical Authority so they shouldn't be able to own by players.
https://prnt.sc/1py3ahh
