### ISSUE TITLE
you can undo letters you make with the undo button

### ISSUE THREAD

**Issue by oscarholmes** [vingard/impulse-issues#12]
**Describe the bug**
letters you make with /write can be removed with z
**To Reproduce**
Steps to reproduce the behaviour:
1. /write test
2. undo with your undo button
3. profit

**Expected behaviour**
destruction of server
**Screenshots**

![image](https://user-images.githubusercontent.com/47502603/52536663-f361eb80-2d5d-11e9-8b83-23d4babca13e.png)

**impulse version (press f1 in the bottom left):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by vingard** [comment]
This is intentional.
