### ISSUE TITLE
Thruster Sound

### ISSUE THREAD

**Issue by revectane** [vingard/impulse-issues#120]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1.  Spawn a Thruster
2. Turn on the Thruster
3. See error

**Expected behaviour**
To hear the sounds correctly and not have them stop after half a second.

**impulse version (press F1 in the bottom right):**
1.71

**Lua error**
N/A

**Additional context**
N/A

**Comment by vingard** [comment]
This seems like an issue you've had with Sandbox, please report it to the Garry's Mod issue tracker.
