### ISSUE TITLE
Death to any flames results in an instant respawn.

### ISSUE THREAD

**Issue by X-Mezo-X** [vingard/impulse-issues#123]
**Describe the bug**
The glitch is basically about anything related to flame damage "env_flame", basically dying to flames would instantly respawn you without you waiting the respawn time, and also it allows for any items or tokens that you have to remain with you without them dropping or being lost.

**To reproduce**
Steps to reproduce the behaviour:
1. Find any source of fire damage (Molotov or map flames).
2. Let the fire kill you.
3. You instantly respawn with full health and still have your items plus tokens still intact in your inventory.

**Expected behaviour**
For some odd reason, you don't lose anything from dying to flames and you respawn instantly.

**Screenshots**
All i have is this horrible clip
https://www.youtube.com/watch?v=aDXp1YHvzjg

**impulse version (press F1 in the bottom right):**
1.71

**Lua error**
Nothing i'm aware of.

**Additional context**
This glitch can effectively allow for a quick suicide when in a risky situation and saving your items from being lost.
Credits to Chad Buffington for informing me of that.

**Comment by vingard** [comment]
Thanks for reporting this, will be hotfixed ASAP.
