### ISSUE TITLE
Door Bug

### ISSUE THREAD

**Issue by UniversalArchitect** [vingard/impulse-issues#135]
**Describe the bug**
Spamming D47 doors will force them open W/O lockpick

**To reproduce**
Steps to reproduce the behaviour:
Go up to any locked door as Civ (not Nexus door) and spam E on it, should take a bit to force it open

**Expected behaviour**
It shouldn't be openable no matter how much it's spammed

**Screenshots**
Video Evidence:
https://streamable.com/dbqrov

**impulse version (press F1 in the bottom right):**
1.74
**Lua error**
Unknown

**Additional context**
N/A

**Comment by X-Mezo-X** [comment]
As far as i'm aware, this is only an issue that happens with Auto-Lock doors, there seems to be a second of time where the door gets unlocked then locked again.

**Comment by vingard** [comment]
impulse has a map script that runs on a looping timer, every few minutes to lock these doors that access the train depot. This isn't due to pressing E, just the timer and your opening line up. This won't be fixed cause it's a very minor bug that has no real effect.
