### ISSUE TITLE
Scoreboard admin menu

### ISSUE THREAD

**Issue by confuseth** [vingard/impulse-issues#15]
**Describe the bug**
Admin menu is visible but doesnt do anything (pressing button doesnt do anything)
Additionally the menu that popups when you click on players through the scoreboard stays open and has to be closed manually

**To Reproduce**
Steps to reproduce the behaviour:
1. Scoreboard and click on someone
2. See the admin menu as regular player

**Expected behaviour**
Have it not be visible at all for non admins

**Screenshots**
![hl2_2019-02-10_18-05-08](https://user-images.githubusercontent.com/25161663/52536743-d8dc4200-2d5e-11e9-9957-3d923883f638.jpg)

**impulse version (press f1 in the bottom left): 0.2**

**Comment by vingard** [comment]
Fixed, thanks for reporting.
