### ISSUE TITLE
Writer effect breaks.

### ISSUE THREAD

**Issue by aLoneWitness** [vingard/impulse-issues#16]
**Describe the bug**
The intro screen repeates the typewriter effect about 5 times.

**To Reproduce**
Steps to reproduce the behaviour:
1. Join server without previously have joined the server.
2. Check the writer effect.

**impulse version (press f1 in the bottom left):**
0.2

**Comment by vingard** [comment]
Ok so this is due to the splash screen if you press more than one key it will make the cutscene process more than 1 time.

**Comment by vingard** [comment]
fixed.
