### ISSUE TITLE
357. Magnum Weapon Problems

### ISSUE THREAD

**Issue by thepersonwhoplaysgames** [vingard/impulse-issues#19]
**Describe the bug**
The "Fists" weap

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**impulse version (press f1 in the bottom left):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by vingard** [comment]
Can you please describe the issue a bit more?

**Comment by vingard** [comment]
This bug is caused by the server running NMod while your client still uses the HL2 weapons so I'll close it. Will be fixed next test. Thanks.
