### ISSUE TITLE
Job text bug

### ISSUE THREAD

**Issue by KirbyTheG** [vingard/impulse-issues#20]
**Describe the bug**
The text to the side that tells you what the job you are selecting is too long and goes off the menu so you can't read it all

**To Reproduce**
Hit F4
go to the Jobs menu
look at the job info

**Expected behaviour**
You should be able to read all the text or scroll it down to read the rest. 

**Screenshots**

![image](https://user-images.githubusercontent.com/18472689/52537012-93ece700-2d2f-11e9-889e-4326bdd818cf.png)

![image](https://user-images.githubusercontent.com/18472689/52537009-80da1700-2d2f-11e9-907a-519e2b265c99.png)

**impulse version (press f1 in the bottom left):**
0.2

**Comment by vingard** [comment]
fixed

**Comment by KirbyTheG** [comment]
[https://youtu.be/wJ2fwP4mKTw](url)
You didn't fix it.
