### ISSUE TITLE
CP #/0.0

### ISSUE THREAD

**Issue by KirbyTheG** [vingard/impulse-issues#21]
**Describe the bug**
The CP value is screwed up in the jobs menu

**To Reproduce**
Steps to reproduce the behaviour:
Go to the jobs menu

**Expected behaviour**
It should say 0 not 0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/18472689/52537060-2bead080-2d30-11e9-9af6-8f5a5c208721.png)

**impulse version (press f1 in the bottom left):**
0.2

**Comment by vingard** [comment]
This has been fixed.
