### ISSUE TITLE
Admin "Goto" button in Player Info menu

### ISSUE THREAD

**Issue by KirbyTheG** [vingard/impulse-issues#22]
**Describe the bug**
You can see the Goto admin button in the Player Info menu

**To Reproduce**
Steps to reproduce the behaviour:
Open player list
Click on a player
Click on the Admin tools drop down

**Expected behaviour**
It should be hidden for normal users

**Screenshots**
![image](https://user-images.githubusercontent.com/18472689/52537131-1033fa00-2d31-11e9-8844-5eaaacd48002.png)

**impulse version (press f1 in the bottom left):**
0.2

**Comment by vingard** [comment]
#15 Already referenced.
