### ISSUE TITLE
Weird Grey Freeman Guy

### ISSUE THREAD

**Issue by qasd-nldw** [vingard/impulse-issues#26]
**Describe the bug**
Players who are in the character creation menu appear as the grey weird model

**To reproduce**
Steps to reproduce the behaviour:
1. Wait until someone joins
2. Wait in spawn
3. See the bug

**Expected behaviour**
You see a grey man. I assume you shouldn't see anything.

**Screenshots**
https://i.gyazo.com/e5eb0cd1a2f26dd199e56ae5d755b590.png

**impulse version (press F1 in the bottom right):**
0.5

**Comment by vingard** [comment]
This is kind of intended as the player has not loaded in. I've ensured grey people are godded so they don't die while loading/in the intro.
