### ISSUE TITLE
LUA error regarding ATM

### ISSUE THREAD

**Issue by greasybreads** [vingard/impulse-issues#28]
**Describe the bug**
Placing nothing but a period in the ATM creates a script error. 

**Lua error**
[ERROR] gamemodes/impulse/gamemode/core/vgui/cl_atm.lua:32: bad argument #1 to 'WriteUInt' (number expected, got nil)
  1. WriteUInt - [C]:-1
   2. DoClick - gamemodes/impulse/gamemode/core/vgui/cl_atm.lua:32
    3. unknown - lua/vgui/dlabel.lua:234

**Comment by vingard** [comment]
Fixed.
