### ISSUE TITLE
Change RP name and Sell all doors button doing nothing

### ISSUE THREAD

**Issue by greasybreads** [vingard/impulse-issues#29]
**Describe the bug**
Both change RP name and Sell all doors fail to do anything upon clicking them. No errors are on the console, nor does anything pop up in chat. Doors are not sold and nothing pops up to change your RP name. 

**Expected behavior**
Clearly these button should work yes?

**Comment by vingard** [comment]
It's not really a bug, it's just that the server-side code is not yet implemented.
