### ISSUE TITLE
/kickdoor works on hidden doors

### ISSUE THREAD

**Issue by vingard** [vingard/impulse-issues#31]
**Describe the bug**
Hidden doors can be kicked in. Allows map doors that lead to nowhere to be opened.

**To reproduce**
Steps to reproduce the behaviour:
1. Find a hidden door
2. Use /kickdoor as CP

**Expected behaviour**
The door to not be kicked in.

**impulse version (press F1 in the bottom right):**
0.5

**Comment by aLoneWitness** [comment]
Fixed.
