### ISSUE TITLE
Convicted Index in the terminal shows all players in the server.

### ISSUE THREAD

**Issue by thepersonwhoplaysgames2** [vingard/impulse-issues#33]
**Describe the bug**
In the Convicted Index menu in the Terminal, the UI shows all players in the server, even if they aren't arrested or put in jail.

**To reproduce**
Steps to reproduce the behaviour:
1. Interact with the Terminal
2. Click on Conv. Index

**Expected behaviour**
It should show only jailed citizens (People who have been imprisoned using the Terminal)

**Screenshots**

**impulse version (press F1 in the bottom right):**
0.5

**Lua error**
If applicable, post the error here in full.

**Additional context**
This may be just because the Terminal isn't finished yet but oh well.
old mike needs to arrest some no-do-gooders

**Comment by vingard** [comment]
fixed.
