### ISSUE TITLE
CmD playermodel still appears even after selecting another rank

### ISSUE THREAD

**Issue by thepersonwhoplaysgames2** [vingard/impulse-issues#34]
**Describe the bug**
When selecting the CmD, in any divison, and selecting another rank, the CmD playermodel is not replaced with the correct playermodel for that rank

**To reproduce**
Steps to reproduce the behaviour:
1. Select a division
2. Click on i4
3. Click on CmD
4. Click on i4 again

**Expected behaviour**
The playermodel should change according to the rank

**Screenshots**
https://i.imgur.com/EuRQrNN.jpg

**impulse version (press F1 in the bottom right):**
0.5

**Lua error**
If applicable, post the error here in full.

**Additional context**
The only way to get rid of this bug is to re-select a division

**Comment by vingard** [comment]
should be resolved.
