### ISSUE TITLE
Ammo Box gives 125 Ammo to every gun

### ISSUE THREAD

**Issue by thepersonwhoplaysgames2** [vingard/impulse-issues#35]
**Describe the bug**
When interacting with the ammo box, it gives you 125 ammo for every gun you have.

**To reproduce**
Steps to reproduce the behaviour:
1. Interect with the ammo box with a gun in your inventory

**Expected behaviour**
You are supposed to get the amount of ammo needed to fill the gun in HL2 (Magnum-12, SMG-225, 9mm-150 etc)

**Screenshots**

**impulse version (press F1 in the bottom right):**
0.5

**Lua error**
If applicable, post the error here in full.

**Additional context**
k im tired im going to go to sleep now

**Comment by vingard** [comment]
fixed
