### ISSUE TITLE
Hands Bug

### ISSUE THREAD

**Issue by elenakatie** [vingard/impulse-issues#37]
**Describe the bug**
Having a phys gun equipped then changing to hand makes you unable to pick up entites.

**To reproduce**
Steps to reproduce the behaviour:
1. Hold a Phys Gun
2. Be next to an entity (Cloth from Factory)
3. Switch to hands then try pick it up
4. Hands are unable to pick stuff up

**Expected behaviour**
Pick stuff up without the restriction

**Screenshots**
N/A

Impulse Version: 0.5

LUA Errors: N/A
If applicable, post the error here in full.

**Additional context**
N/A.

**Comment by vingard** [comment]
i'll try to see if i can find out why this happens post release. it's a weird bug.
