### ISSUE TITLE
Combine interface bug

### ISSUE THREAD

**Issue by Lukyn150** [vingard/impulse-issues#39]
**Describe the bug**
As Unranked OTA you can only see city status and citizen count on combine interfaces but nothing else. Like buttons.

**To reproduce**
Steps to reproduce the behaviour:
1. Become OTA
2. Go to a combine interface
3. bug

**Expected behaviour**
It should show buttons like bulletin

**Screenshots**

**impulse version (press F1 in the bottom right):**
0.5
**Lua error**
[ERROR] gamemodes/impulse/gamemode/core/sh_teams.lua:386: attempt to index a nil value
  1. GetTeamRankName - gamemodes/impulse/gamemode/core/sh_teams.lua:386
   2. SetupUI - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalmenu.lua:63
    3. func - gamemodes/impulsehl2rp/schema/scripts/hooks/cl_hooks.lua:15
     4. unknown - lua/includes/extensions/net.lua:32

**Additional context**

**Comment by vingard** [comment]
fixed
