### ISSUE TITLE
Arrest bug

### ISSUE THREAD

**Issue by elenakatie** [vingard/impulse-issues#40]
**Describe the bug**
Checking the arrest menu for Citizens causes lua errors.

**To reproduce**
Steps to reproduce the behaviour:
1. Arrest Someone
2. Give them violation charges (gave them 243 for the test)
3. Open Terminal
4. Go to Conv Index

**Expected behaviour**
Display the right information? Idk

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/920331435130479204/57B4E1A374C252FC9741D908A8F097394C815976/

Impulse Version: 0.5

**Lua error**

[ERROR] gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84: attempt to call method 'GetSyncVar' (a nil value)
  1. unknown - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84

[ERROR] gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84: attempt to call method 'GetSyncVar' (a nil value)
  1. unknown - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84

[ERROR] gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84: attempt to call method 'GetSyncVar' (a nil value)
  1. unknown - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalplayer.lua:84

**Comment by vingard** [comment]
fixed
