### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Lukyn150** [vingard/impulse-issues#42]
**Describe the bug**
 error spam

**To reproduce**
Idk started randomly
**Expected behaviour**
not appear

**Screenshots**
-

**impulse version (press F1 in the bottom right):**
0.5
**Lua error**
[ERROR] gamemodes/impulsehl2rp/entities/entities/impulse_hl2rp_cp_npc/cl_init.lua:52: attempt to call method 'createBubble' (a nil value)
  1. unknown - gamemodes/impulsehl2rp/entities/entities/impulse_hl2rp_cp_npc/cl_init.lua:52

**Additional context**

**Comment by vingard** [comment]
Fixed.
