### ISSUE TITLE
Combine OTA terminal bug

### ISSUE THREAD

**Issue by tomuu** [vingard/impulse-issues#45]
**Describe the bug**
Essentially not being able to arrest citizens as OTA as it bugs the game.

**To reproduce**
1. Have a citizen restrained as ota and move him to the terminal
2. Click on the terminal.

**Expected behaviour**
Expected the normally the menu appear to detain citizen without it causing script errors and not being able to detain.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.01
**Lua error**
[ERROR] gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalmenu.lua:293: attempt to index local 'newSheet' (a nil value)
  1. AddTab - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalmenu.lua:293
   2. SetupUI - gamemodes/impulsehl2rp/schema/scripts/vgui/cl_terminalmenu.lua:261
    3. func - gamemodes/impulsehl2rp/schema/scripts/hooks/cl_hooks.lua:23
     4. unknown - lua/includes/extensions/net.lua:32

**Additional context**
N/A

**Comment by vingard** [comment]
fixed
