### ISSUE TITLE
Storage items dissapearing bug

### ISSUE THREAD

**Issue by ChobaniYogurt** [vingard/impulse-issues#46]
**Describe the bug**
Through-out the past two days, I've had stuff stashed in my Storage Container in my apartment. Over a little while, I'll rejoin the server and come back to a container, only to have several items missing out of them for an unknown reason. I had 5 axes in there at one point, I rejoin, they're all gone. And this morning, I rejoin, go into my container, and my Pistol Ammo, and FIFTY metal plates have all vanished, without a trace. I have no idea why this is happening.

**To reproduce**
I have no idea how to reproduce the bug. The only thing that I think could be affecting it, is I'm always on the server when the daily restarts happen, at around 4 AM for you. The server instantly shuts down when that happens and its possible that might glitch out the MySQL or something.

**Expected behaviour**
I have no idea why its happening.

**Screenshots**

**impulse version (press F1 in the bottom right):** 1.02

**Lua error**

**Additional context**
I am not a donator, and I have over 900 XP on the server, I promise this isn't some type of bait. I've been playing the server non-stop for the past two days, and I just really don't want my items that I've been gathering to dissapear, and waste a TON of progress.

**Comment by vingard** [comment]
fixed
