### ISSUE TITLE
Vortigaunt VIP bug

### ISSUE THREAD

**Issue by Locy2222222222** [vingard/impulse-issues#47]
**Describe the bug**
Basically your able to become a vortigaunt even without VIP

**To reproduce**
Steps to reproduce the behaviour:
1.Press F4
2.Click Team
3.Click Vortigaunt
**Expected behaviour**
Not allowing me to become a vortigaunt

**Screenshots**
![image](https://user-images.githubusercontent.com/58259736/69725559-6d325c80-1159-11ea-909e-4e13331c7d67.png)

**impulse version (press F1 in the bottom right):**
1.02

**Lua error**
N/A

**Additional context**
I found this glitch by accident I was going to switch to the CA but accidently click vortigaunt instead

**Comment by vingard** [comment]
fixed
