### ISSUE TITLE
City Administrator Being Full Bug

### ISSUE THREAD

**Issue by Locy2222222222** [vingard/impulse-issues#48]
**Describe the bug**
Every time when I tried to become a CA it says jobs full even when it isn't full and no one was playing CA 

**To reproduce**
Steps to reproduce the behaviour:
1. Must be non VIP
2. Press F4
3. Click Teams
4. Click on the job "City Administrator"

**Expected behaviour**
Allowing me to become the CA

**Screenshots**
![image](https://user-images.githubusercontent.com/58259736/69807605-b00b3780-1220-11ea-9ea8-4d9ce3d07358.png)

**impulse version (press F1 in the bottom right):**
1,02

**Lua error**
N/A

**Additional context**
In the screenshot if you look at the bottom right you can see that it said City Administrator is full
even when it isn't

**Comment by vingard** [comment]
fixed in 1.1
