### ISSUE TITLE
Rogue can give you full ammo

### ISSUE THREAD

**Issue by EnigmaFusion1** [vingard/impulse-issues#49]
**Describe the bug**
If you are a rebel and have a gun in your inventory, you are able to be detained and then undetained which causes the max amount of ammo to be inserted into your weapon. 

**To reproduce**
Steps to reproduce the behaviour:
1. Get 1 rebel with gun and 1 cp. 
2. Get rebel to equip gun with no ammo in gun. 
3. Get CP to cuff rebel. 
4. Get CP to uncuff rebel. 
5. See ammo in gun
6. See error?

**Expected behaviour**
If you arrest and unarrest a rebel with a weapon, it is expected that it doesn't affect their ammo. 

**Screenshots**

**impulse version (press F1 in the bottom right):** https://gyazo.com/da6558d44c28a3367abbf1d1490a4f41

**Lua error**
If applicable, post the error here in full.

**Additional context**
Pretty easy to do, vingard u better fix this immediately

**Comment by vingard** [comment]
fixed ty
