### ISSUE TITLE
F4 not opening a menu

### ISSUE THREAD

**Issue by confuseth** [vingard/impulse-issues#5]
**Describe the bug**
F4 is blank on initial opening
cant click "Action" button to open that menu

**To Reproduce**
Steps to reproduce the behaviour:
1. Press F4
2. Cant click "Action" button

**Expected behaviour**
Expected to see the previous or the first menu popup

**impulse version (press f1 in the bottom left): 0.2**

**Comment by vingard** [comment]
This issue has been fixed. Thanks for reporting it.
