### ISSUE TITLE
Bug with the BOL system.

### ISSUE THREAD

**Issue by NforceSSP** [vingard/impulse-issues#50]
Description: If you get a BOL on you and you get arrested, when you are released you still have a BOL.

Steps:
1. Get BOL'd
2. Get arrested
3. Go to a camera after you got released

Expected behaviour: BOL is supposed to be removed after getting released from jail.

Version: 1.34

**Comment by vingard** [comment]
Were you actually sent to jail when arrested?

**Comment by NforceSSP** [comment]
Yes.

**Comment by NforceSSP** [comment]
Got an actual recording (sorry for low res/lag, don't have a good pc)

[https://www.youtube.com/watch?v=rV0jz4gyByQ&feature=youtu.be](url)

**Comment by vingard** [comment]
Thanks for the video, I'll investigate this again for a fix in update 1.4 :)

**Comment by vingard** [comment]
Fixed.
