### ISSUE TITLE
Cannot remove CPs/OTAs from doors when they were added as Citizen.

### ISSUE THREAD

**Issue by ovxy** [vingard/impulse-issues#51]
Issue explained in the title.

1. Buy a door
2. Add someone
3. Said someone goes Civil Protection/OTA
4. They aren't removed from the door automatically

When they do sell all doors in the F4 menu a message about selling a door for 0T pops-up.

They are still added to the door and there is no way to remove them when using the F2 door menu, clicking on their name in the remove section does nothing.
The only way to remove them is by selling the whole door.

Aren't they supposed to be removed automatically? I noticed this happens on standalone doors that don't require a terminal to purchase ex. Grizzly Grotto doors.

Impulse ver: 1.34

Extra notes: If said person goes back to Citizen they can't access storage containers if one is bound to a door (might be caused by pressing sell all doors)

**Comment by vingard** [comment]
Fixed. Thanks.
