### ISSUE TITLE
Issue with Arrests.

### ISSUE THREAD

**Issue by Candyexin** [vingard/impulse-issues#52]
> Bug Details

Description:
When you unzip a user before they get teleported to jail, the user is stuck in jail with access to all their UI stuff (Inventory, Building etc.) and also do not have a timer to view how long is left on their current sentance.

Re-creation Steps:
Arrest a Citizen, take them to a terminal. When you are at the terminal charge them for any violation. Before they get teleported, remove their zipties.

Not only does this remove your Timer, it also allows you to see your inventory, and build.

This is great hindrance to users and staff alike.

Impulse Version: 1.34

**Comment by vingard** [comment]
Will be fixed in 1.4.
