### ISSUE TITLE
Impulse Stacker-Improved Bug

### ISSUE THREAD

**Issue by Engineer05** [vingard/impulse-issues#54]
**Describe the bug**
When you select the Stacker tool and start using it, for some reason, it makes you pay the double for one prop.

**To reproduce**
Steps to reproduce the behaviour:
1. Open the Menu and Select Stacker Tool
2. Once select the tool, press left-click on a prop to stack it
3. After that, it would make you pay the double for one prop

**Expected behaviour**
After you stack a prop, it should just make you pay 5 tokens instead of 10.

**Screenshots**
Video: https://youtu.be/AUQP54V9slE

**impulse version (press F1 in the bottom right):**
Impulse 1.34

**Lua error**
If applicable, post the error here in full.
None

**Additional context**
Nop

**Comment by vingard** [comment]
Fixed. Thanks.
