### ISSUE TITLE
Numpads dont work on impulse in terms of wiring

### ISSUE THREAD

**Issue by DoggoGaming1** [vingard/impulse-issues#57]
**Describe the bug**
Wire Numpads do get activated in terms of the button being registered but the Connection to something does not work, when playing Singleplayer the Wire works normally
**To reproduce**
Steps to reproduce the behaviour:
1. make a simple Numpad contraption (Numpad to thruster)
2. Hit button assigned to Numpad
3. Nothing happens

**Expected behaviour**
What is meant to happen is the Thruster gets activated.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
Impulse 1.34

P.S None of the other question come with anything

**Comment by vingard** [comment]
This system is for issues with the framework or schema, not addons. Sorry.
