### ISSUE TITLE
"From The Grave" Achievement broken.

### ISSUE THREAD

**Issue by SmugBruh** [vingard/impulse-issues#58]
Me and Keegar was trying to get the "From the grave Achievement" but for some

Steps to reproduce the behaviour:
1. Have someone consent to help you with the achievement
2. Get a Molotov 
3. Have both of you low health.
4. You throw the Molotov at yourself, killing you, Then have your friend go in after you die.

**Expected behaviour**
It didn't gave me the achievement at all.

**Screenshots**
I don't have any screenshots nor video, keegar might have some.

**impulse version:**
1.34
**Lua error**
None of what I can see.
**Notes**
I've made this pretty late so sorry if I might have some misspells or grammar issues.

**Comment by vingard** [comment]
Fixed.
