### ISSUE TITLE
Helix SQL doesnt get its medkit

### ISSUE THREAD

**Issue by OwlACEB** [vingard/impulse-issues#59]
Simple enough, SQL just doesnt get a medkit

1. Go to Class/Rank picker
2. Click on Helix/SQL
3. Check Inventory
4. No Medkit

Version 1.34

Image
![Explain please](https://user-images.githubusercontent.com/68160441/92513656-8591d600-f1c5-11ea-9f6c-2ab1bbc029ca.jpg)

**Comment by vingard** [comment]
The medkit is not an inventory item, it is just a weapon. This is intended.
