### ISSUE TITLE
arrest spawn broken

### ISSUE THREAD

**Issue by tonybalogne** [vingard/impulse-issues#60]
When arrested, you spawn outside the laundromat in an alley.

To reproduce Steps to reproduce the behaviour:

Get arrested
You will spawn outside laundromat in an alley

Screenshots If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/70239784/93658045-03e04a80-fa06-11ea-94a3-4fba8c5652b2.png)

impulse version (press F1 in the bottom right): 1.4

Lua error If applicable, post the error here in full.

Additional context Add any other context about the problem here.
I was arrested alongside someone else for trespassing on train tracks and they were also teleported here, I'm pretty sure this happens to everyone though I have only one other person to confirm they've spawned where the screenshot is.
Also, this happened 30 minutes ago after the 1.41 update

**Comment by vingard** [comment]
Fixed.
