### ISSUE TITLE
Appartment Chest 

### ISSUE THREAD

**Issue by ohyeahjucie** [vingard/impulse-issues#61]
**Describe the bug**
you can use appartments chests without being the owner of such appartment, you can even use unowned appartment chest while having a house in that appartment block

**To reproduce**
Steps to reproduce the behaviour:
1. Go to an appartment block
2. Click on buy a house
3. go to any appartment of the appartment block
4. open the chest of the house that is not yours

**Expected behaviour**
it supposed to not let me use the chest because i was not the owner of the house

**Screenshots**
![image](https://user-images.githubusercontent.com/71799257/94087386-f949fa80-fde3-11ea-88de-b75d38616b0f.png)
![image](https://user-images.githubusercontent.com/71799257/94087421-18488c80-fde4-11ea-8345-d8cf65a7803f.png)
![image](https://user-images.githubusercontent.com/71799257/94087451-2bf3f300-fde4-11ea-9235-623ec06759a3.png)

**impulse version (press F1 in the bottom right):**
impulse version: 1.4

**Lua error**
none
**Additional context**
none

**Comment by ohyeahjucie** [comment]
update: it only seems to happen in the appartments near the hospital, also, everytime you use an apartments chest that isnt yours it will automatically remove your appartment keys without refund

**Comment by vingard** [comment]
Fixed.
