### ISSUE TITLE
Blue rebel suit broken. 

### ISSUE THREAD

**Issue by ovxy** [vingard/impulse-issues#62]
The blue rebel suit which can be worn by using E2 to edit bodygroups is broken.
It doesn't get detected on Combine Cameras and people wearing it can make requests. 
![unknown](https://user-images.githubusercontent.com/69227587/94407560-e0d73880-0173-11eb-9fc4-31f9c89f640f.png)

**Comment by vingard** [comment]
This is not a bug, it's a result of E2 abuse. Please don't use E2 to modify your rebel suit in this way.
