### ISSUE TITLE
Storage bug. 

### ISSUE THREAD

**Issue by ovxy** [vingard/impulse-issues#63]
Maximum on-person storage capacity sometimes decreases to 19.9 kg despite it being displayed as 20 kg.
The only known way to solve this issue is by re-joining. I do not recall anyone else encountering this issue.
It's hard to provide image evidence as this issue occurs at random. Today was the first time I encountered it in a long time.
I don't know what might cause this issue.
Because of this bug I am unable to equip things like ammunition while having 19 kg of items on me.

**Comment by vingard** [comment]
Please use the format.
