### ISSUE TITLE
Storage Bug #2. 

### ISSUE THREAD

**Issue by ovxy** [vingard/impulse-issues#64]
**Describe the bug**
Sometimes on-person maximum storage capacity decreases from 20 kg to 19.9 kg making it not possible to equip 1 kg items while already having 19 kgs of items in inventory. 

**To reproduce**
Steps to reproduce the behaviour:
1. Equip 19 kg of times (ex. Mk3 helmet, Shotgun, gas mask and OTA vest) 
2. Attempt to equip a 1 kg item 

**Expected behaviour**
I'm supposed to equip the 1 kg item as I still have enough space as shown by the maximum capacity indicator (19kg/20kg).

**Screenshots**
None. 

**impulse version (press F1 in the bottom right):**
1.42

**Lua error**
N/A

**Additional context**
This issue occurs at random and I don't know of any specific way to make it happen.

**Comment by vingard** [comment]
I've attempted to replicate this, but cant, if it happens again please DM me on Discord and I can investigate it live if I have the time.

**Comment by ovxy** [comment]
I will, also Jackie (another member of the community) told me that they have been encountering this issue alot recently if you want to inquire about it their discord is:
Jackie ♡#6969

513194198560931872 <- their discord ID if the username above doesn't work due to special characters in the name.

**Comment by vingard** [comment]
@ovxy Thanks, if you could please link them this issue and pass on my message above. Remember, if it does happen again, don't do anything to change it if possible until I can check. If I don't respond after 10ish minutes you might wanna just continue playing as that means I'm probably busy with something else.
