### ISSUE TITLE
Movement is faster on the right on pick up that can

### ISSUE THREAD

**Issue by lokachop** [vingard/impulse-issues#65]
**Describe the bug**
While playing pick up that can, your speed towards the right is abit faster than to the left

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the F1 menu and activate pick up that can
2. Move to the left then to the right
3. See that you move faster to the right than to the left

**Expected behaviour**
Both should move at the same speed

**Screenshots**

**impulse version (press F1 in the bottom right):**
![image](https://user-images.githubusercontent.com/69372103/95747427-bc617d00-0c98-11eb-9803-108a57538c79.png)

**Lua error**
no error 

**Additional context**
really minor problem but its very annoying while trying to beat pick up that can regardless

**Comment by vingard** [comment]
This is a weird bug I was aware of at the time and seems simple but no fix was found. Since it's so minor imma just leave it like this. Thanks anyway.
