### ISSUE TITLE
Cameras not focusing on players

### ISSUE THREAD

**Issue by ovxy** [vingard/impulse-issues#66]
**Describe the bug**
Cameras are not focusing on some players.

**To reproduce**
Steps to reproduce the behaviour:
1. Come up to a camera
2. Stare at it panning 
3. Camera ignores you  

**Expected behaviour**
Cameras are supposed to focus on all players and if said player has contraband equipped they should be detected.

**Screenshots**
https://www.youtube.com/watch?v=e4FcHoQ3aTg
Not a screenshot but oh well (Video provided by CornOfAllFields)

**impulse version (press F1 in the bottom right):**
1.43

**Lua error**
N/A
**Additional context**
N/A

**Comment by vingard** [comment]
This happens sometimes. It's a issue I can't fix as we basically just piggy-back the HL2 cameras.
