### ISSUE TITLE
Getting over the wall that is blocking the way out of the city

### ISSUE THREAD

**Issue by ATLIENKING** [vingard/impulse-issues#69]
**Describe the bug**
when you get over it you easily  can hide from anyone   for me thats fail rp we heard a grid that was stuck in there and we helped him

**To reproduce**
Steps to reproduce the behaviour:
1. you need 2 players
2. 1 player need to crouch  and the other player need to jump on it and he get on the wall and jump the other side

**Expected behaviour**
i excpeted to  people building  some things and to get over it  but  you need 2 players

**Screenshots**
https://imgur.com/a/M6Hcu3p

**impulse version 1.43**

**Lua error**
N/A

**Additional context**
N/A

**Comment by ATLIENKING** [comment]
there is bug that you step on the sky when you jump from the player and then you can enter the other side

**Comment by vingard** [comment]
This is for bugs with the framework or schema.
