### ISSUE TITLE
Revolver Ammo bug

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#70]
**Describe the bug**
If you shot the Revolver and then switch to another job, it will have max ammo in the magazine, although you shot it.

**To reproduce**
1. Get a revolver
2. Load it
3. Shoot it like 3-4 times
4. Switch job (to CWU, if you are a citizen)
5. Check the weapon
6. See glitch

**Expected behavior**
It should reset the ammo's magazine, like the M60 (yes, I tested it with the M60 and when I switched jobs, the ammo got reset to 0)

**Screenshots**
https://streamable.com/k0xgu5

**impulse version (press F1 in the bottom right):**
https://prnt.sc/vruwks

**Lua error**
No LUA error

**Additional context**
vin pliz fix

**Comment by vingard** [comment]
Thanks for your bug report. This issue has been fixed in 1.51. 👍
