### ISSUE TITLE
Moonshining in water

### ISSUE THREAD

**Issue by WarningRope6569** [vingard/impulse-issues#71]
**Describe the bug**
I tried to moonshine in the water but it didn't work and it took my resources that i put in the barrel

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'sewers and place barrels in water'
2. Click on 'the items and it will take your items'

**Expected behaviour**
i thought it would come up with an error but it didnt
**Screenshots**

**impulse version (press F1 in the bottom right):**
1.43
**Lua error**
If applicable, post the error here in full.

**Additional context**
AVX saw and could say what happened in more detail

**Comment by vingard** [comment]
Placing moonshine in the water will spoil it. This is intended.
