### ISSUE TITLE
Moderation Improvement 

### ISSUE THREAD

**Issue by UniversalArchitect** [vingard/impulse-issues#72]
**Describe the bug**
A clear and concise description of what the bug is:
I'm reporting issues that people use to reveal Moderators and so im creating this to help.

Explanation: Throughout Impulse and my journey I've witnessed a couple of problems that reveal Moderators. 
1- Physics gun exposure:
When a Moderator is in Noclip, They usually equip hands or a weapon, However when switching to Physics gun while in incognito, Their Blue Light reveals them and people are more aware and try to act not mingy 

2- Thirdperson Moderator Reveal glitch
Usually when people go thirdperson (Which is 60% of the time), They run around doing random things, If in combat however they may use it to reveal a Moderator, How this works is that when you don't look around or your thirdperson Camera zooms in, with no objects or barricades behind you, it reveals Moderators are watching you. 

3- F3 Abuse:
I have never tried this and never will however some people act to get stuck if they're not sure that a Moderator is on incognito or truly no Moderators online. They use Elevators or stairs in Maps to pretend getting stuck in order to find out if its their chance to Minge or not.

4- E2 Exposure:
As known, E2s are a hologram that make you look fancy and/or better. However weapon holster holograms sometimes mess up Noclip invisibility. You start seeing flying Weapons and/org Hats.

Note: I explained this to a Moderator back in D47 but I have no idea if He/She stated it to you. 

**Expected behaviour**
Not much, I just wanted to help out.
**Screenshots**
Unavailable, Its too hard to get a Screenshot of all 4 issues
**impulse version (press F1 in the bottom right):**
1.5
**Lua error**
If applicable, post the error here in full.
N/A
**Additional context**
N/A

**Comment by vingard** [comment]
I appreciate your trying to help, but this is for the forums. This is for technical bugs only.
