### ISSUE TITLE
Combine Radio Voicelines issue

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#73]
**Describe the bug**
The bug consists of this: You are an i4 and you tye /rcmd 4 20 60 9. The issue is that the voice lines are still played and can be heard by the commanding units and the i4.

**To reproduce**
Steps to reproduce the behaviour:
1. Go CP/OTA
2. Type /rcmd and a voice line
3. Listen carefully

**Expected behaviour**
It shouldn't play the voice lines at all.

**Screenshots**
No screenshots.

**impulse version (press F1 in the bottom right):**
1.5

**Lua error**
No LUA errors

**Additional context**
If needed, I can post a video recording.

**Comment by vingard** [comment]
Thanks for the report, this bug has been fixed in 1.61!
