### ISSUE TITLE
Outdated Guides

### ISSUE THREAD

**Issue by Lukyn150** [vingard/impulse-issues#75]
**Describe the bug**
Crafting has no content
How to get your first 500 tokens is WIP for too long
Changing your character/skin has outdated information

**To reproduce**
Steps to reproduce the behaviour:
-

**Expected behaviour**
No outdated info on important topics
If a guide is listed a guide is there

**Screenshots**
-

**impulse version (press F1 in the bottom right):**
1.5

**Comment by vingard** [comment]
Sorry those guides are maintained by the Community Manager (Jamsu), please contact him about it. This is for technical framework/schema issues.
