### ISSUE TITLE
Inventory Pop Up Bug

### ISSUE THREAD

**Issue by MrBlizzard1257** [vingard/impulse-issues#76]
**Describe the bug**
The inventory pop up will stay on your screen if you switch jobs whilst still having the inventory menu open.

**To reproduce**
Steps to reproduce the behaviour:
1. Open up your inventory.
2. Open up F4 whilst still holding C.
3. Change to any job. (I changed from CP to OTA)
4. Bug will exist.

**Expected behaviour**
I expected the new inventory to replace the old one but it didn’t.

**Screenshots**
https://cdn.discordapp.com/attachments/710191371855593555/800417399836115043/20210117172529_1.jpg

**impulse version (press F1 in the bottom right):**
1.6

**Lua error**
N/A

**Additional context**
Not tried it with any other factions, I was CP changing to OTA.

**Comment by vingard** [comment]
I can't open the F4 menu when I hold C. Are you sure this is possible?

**Comment by MrBlizzard1257** [comment]
I managed to do it so yeah.

**Comment by vingard** [comment]
I can't replicate it so I can't deal with it unfortunatley.
