### ISSUE TITLE
Jail Teleportation

### ISSUE THREAD

**Issue by DrWeirdlove** [vingard/impulse-issues#77]
**Describe the bug**
Restrained players when charged with a crime sometimes do not teleport to jail.

**To reproduce**
Steps to reproduce the behaviour:
1. Restrain someone
2. Charge them with a crime

**Expected behaviour**
They do not teleport to jail even though they have been charged and a sentence begins for them.

**Screenshots**
https://youtu.be/Ewc3xmuV5tc
https://youtu.be/Mn82ibANqyQ

**impulse version (press F1 in the bottom right):**
1.6
**Lua error**
None

**Additional context**

**Comment by vingard** [comment]
I've tried to replicate this but can't skimming through the code I can see what might be causing it so I've deployed a possible fix in 1.61. Thanks.
