### ISSUE TITLE
Bugged equipped items

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#78]
**Describe the bug**
Certain players can have a face wrap and a riot helmet equipped (and their qualities too) without them being in the inventory. 

**To reproduce**
Steps to reproduce the behaviour:
1. Find a player with these items equipped
2. Try search (if Combine)
3. Bring the player to the camera (it also pings him)

**Expected behaviour**
This shouldn't be happening. You need to have the respective items in inventory to have them equipped.

**Screenshots**
https://streamable.com/9678v5
https://prnt.sc/xt6770

**impulse version (press F1 in the bottom right):**
1.6 (latest)

**Lua error**
None

**Additional context**
I'm sure this isn't a clientside error.

**Comment by vingard** [comment]
Fixed in 1.61 thanks.
