### ISSUE TITLE
Bug that can Gain you super speed

### ISSUE THREAD

**Issue by ATLIEN101** [vingard/impulse-issues#79]
**Describe the bug**
The Bug i found it when i jumped on  stairs and the stairs like throwed me forward with super speed 
**To reproduce**
find stairs, start walking forward while bhopping on the stairs , and the stairs will  throw you forward with super speed

**Expected behaviour**
I expect when people are chased by someone or cps  that they will use the bug to gain speed and get away.

**Screenshots**
N/A ( i will be banned if someone see me trying it )

**impulse version: 1.61**

**Lua error**
N/A

**Additional context**
It's very hard but it's possible   and if you continue Bhopping when the stairs throwed you forward, you will be able to  be very fast like in Half life speedrun

Contact me on steam or Discord  to tell me how to show it if you cant do it

**Comment by lokachop** [comment]
That's not an impulse related issue, that happens also in base GMOD.

**Comment by vingard** [comment]
> 
> 
> That's not an impulse related issue, that happens also in base GMOD.

This pretty much, this isn't a bug, thanks anyway.
