### ISSUE TITLE
Chatbox Text is fading while open

### ISSUE THREAD

**Issue by confuseth** [vingard/impulse-issues#8]
**Describe the bug**
The text in the chatbox while open fades away and then jumps back to full opacity

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the chat box
2. Wait a few seconds
3. See the text fading

**Expected behaviour**
Expecting it not to fade or blink

**Comment by vingard** [comment]
This is due to InsertFade and ResetAllFades being super limited and having weird behaviour. The chat will be changed from a rich text system to a markdown based system to fix this, probably before the next test.

**Comment by vingard** [comment]
Chatbox richtext has been re-coded and this issue has been fixed.
