### ISSUE TITLE
Arrest Glitch

### ISSUE THREAD

**Issue by kingdarkness4521** [vingard/impulse-issues#80]
The bug happens when the user in question is un-detained right after they have been charged.
In the couple of seconds before being charged, the player is able to change jobs using the F4 menu, once they are in jail, they will be able to leave and pick a class from the respective NPC regardless of the jail sentence. 

**To reproduce**
Steps to reproduce the behaviour:
1. You will have to get arrested and un-detained right before being charged.
2. Press F4 and change jobs while Overwatch Voice is giving the charges.
3. Become CP / OTA job
4. Proceed to go to an NPC of the respective class and pick a division.

**Expected behaviour**
Expected this to restrict players from doing so in the first place.

[https://imgur.com/zH2uW0e](url)

**Additional context**
I dont have anything else to add.

**Comment by vingard** [comment]
Thanks will test soon!

**Comment by vingard** [comment]
Fixed.
