### ISSUE TITLE
Weapon Detain Glitch

### ISSUE THREAD

**Issue by F3t0r** [vingard/impulse-issues#86]
**Describe the bug**
Having a weapon not show up in your inventory but still acts as if it's equipped and usable as a citizen.

**To reproduce**
1. Have a weapon on you equipped
2. Get zip-tied by a CP
3. Get released without being searched

**Expected behavior**
Not being able to have access to the weapon post-zip tieing

**Screenshots**
https://imgur.com/a/h9n2xEH
https://imgur.com/a/EFAk7UT
https://imgur.com/a/godBrZ0
**impulse version (press F1 in the bottom right):**
1.61

**Lua error**
None

**Additional context**
As shown in the third screenshot, you get picked up by the cameras around the map but don't alert CPs at all.

**Comment by vingard** [comment]
This is a weird source engine desync thingy I think, so I can't replicate it or fix it afaik. Thanks anyway.
