### ISSUE TITLE
Going over the weight limit

### ISSUE THREAD

**Issue by Tomitson** [vingard/impulse-issues#87]
**Describe the bug**
A bug which allows you to go over the weight limit

**To reproduce**
Steps to reproduce the behaviour:
1. Get bunch of items in your inventory as civie (like something of a 19/20kg)
2. Change to CP job
3. Go to rank giver and take union i1
4. You are now over the weight limit

**Expected behaviour**
Exactly what happened

**Screenshots**
https://cdn.discordapp.com/attachments/807364904502820938/816963565391052810/unknown.png
https://www.youtube.com/watch?v=f-8lBmn4K2o&ab_channel=Tomitson

**impulse version (press F1 in the bottom right):**
1.61
**Lua error**
N/A

**Additional context**
N/A

**Comment by vingard** [comment]
This is intended and isn't a bug.
