### ISSUE TITLE
/RCMD broken for LDR

### ISSUE THREAD

**Issue by SSteffan** [vingard/impulse-issues#89]
**Describe the bug**
LDR Units can type in /rcmd and send messages in it
but they can not see any text that is put into /rcmd by themselfs or others

**To reproduce**
Steps to reproduce the behaviour:
press Y or U
type "/rcmd [text here]"
press enter

**Expected behaviour**
You do not see anything
but the message is sent and can be read by DVL+
but you can not see their messages or your own
this has been a bug since DcO was added

**Screenshots**
https://cdn.discordapp.com/attachments/803332839407353886/822528308259979324/20210319175219_1.jpg

https://cdn.discordapp.com/attachments/822528190173020160/822528198779600906/unknown.png

**impulse version (press F1 in the bottom right):**
1.61

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by vingard** [comment]
Fixed in 1.62, thanks!
