### ISSUE TITLE
Shadow Texture Glitch

### ISSUE THREAD

**Issue by hoon3r** [vingard/impulse-issues#94]
**Describe the bug**
A shadow that appears out of the sky that looks like spread/spaced-out textures and starts to flash wildly.

**Expected behaviour**
After a couple of minutes, say 5 minutes, it starts to appear, making it almost impossible to concentrate because of the flashing shadows. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81934598/113523173-20a52f80-959e-11eb-9efc-132081ab834b.png)
![image](https://user-images.githubusercontent.com/81934598/113523189-36b2f000-959e-11eb-8052-9ca6380f02d6.png)
![image](https://user-images.githubusercontent.com/81934598/113523280-c6f13500-959e-11eb-912c-55c0cfe45f0e.png)

I've used the r_shadows 1 command and verified the GMod files, but that didn't help.

**Comment by vingard** [comment]
Hey, this is a clientside issue and isn't caused by the gamemode. Sorry.
