### ISSUE TITLE
Facewraps not working against jury investigations

### ISSUE THREAD

**Issue by LoganSin117** [vingard/impulse-issues#95]
Juries being able to investigate corpses and bypass facewrap identity protection.

I've only seen the bug once and haven't been able to reproduce it, but from what I've been told by an OfC who was there when it happened the jury investigated the CP I had killed and it said I had killed him. I was not automatically BOLed and it had to be done manually but it still said I had killed the CP.

I expected the jury investigation not to find my identity as I was wearing a facewrap.

I did not take any screenshots and even if I did I don't think they would be very helpful.

Version 1.62

I did not find any errors in the console.

I was shotcopping with a friend and we were both using facewraps. After killing about 4 CPs I escaped at 9HP with him and after returning to the city from theatre an i3 told me I had a BOL on me for 243 and I was arrested. After PMing an OfC who was on at the time he explained that the jury had only said I had killed the CP and I was not automatically BOLed.

**Comment by vingard** [comment]
Please use the format.
