### ISSUE TITLE
Given Rations frees citizen from cuffed.

### ISSUE THREAD

**Issue by MinxBright** [vingard/impulse-issues#96]
When the citizen was cuffed, and given the ration while cuffed freed the citizen from cuffs.

This is something I never expected to happen, but I thought the CP have uncuffed him but I found out it didn't. 

I thought you able to get rations (eat) while cuffed and still be cuffed or it won't work.

The Relay (Shadowplay) video corrupted but there are witnesses. Two or Three CPs and the citizen that got freed in the bug. 

V1.62

N/A 

Hopefully this will be fixed. Thanks~!

**Comment by vingard** [comment]
I've tried replicating this and it doesnt happen. Please also use the format next time.
