### ISSUE TITLE
Name "blocked" not blacklisted

### ISSUE THREAD

**Issue by MixGaming25** [vingard/impulse-issues#98]
**Describe the bug**
So you can name yourself "blocked" that is the same thing as "world" for example if admin looks at door/button it will say "blocked" but if the player spawns something named blocked it can cause some trouble.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to f4
2. Click on change rp name
3. type in "blocked"

**Expected behavior**
So that it will be backlisted same as "world"

**Screenshots**
https://ibb.co/D9mb4sX (here you will see that blocked is green but thats because all props placed by the player that looks at it will be green, if other player named blocked placed it, it would be the same as that door)
https://ibb.co/Bgjrfg8

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
I spent 120T for name change/demonstration

**Comment by vingard** [comment]
Thanks for reporting this, will be fixed in 1.7!
