### ISSUE TITLE
F6 Squads issue #1

### ISSUE THREAD

**Issue by 1avx1** [vingard/impulse-issues#99]
**Describe the bug**
You can hear the voicelines of OTA if you are CP in a squad and viceversa

**To reproduce**
Steps to reproduce the behaviour:
1. Go CP/OTA
2. Get rank
3. Get in a squad
4. Type a voiceline in Squad Radio
5. See error

**Expected behaviour**
You should not hear the voiceline

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.62

**Lua error**
N/A

**Additional context**
N/A

**Comment by vingard** [comment]
Fixed this (and the same issue /rcmd had) in 1.7. Thank you.
